### ISSUE TITLE
proxy函数没用调用

### ISSUE THREAD

**Issue by shaomaicheng** [bytedance/android-inline-hook#20]
### ShadowHook Version

1.0.3

### Android OS Version

11

### Android ABIs

armeabi-v7a, arm64-v8a

### Device Manufacturers and Models

pixel2xL

### Describe the Bug

demo里面hook了 android_get_device_api_level, 结果显示hook成功了，但是proxy没有执行。请问是使用不对么。
```
cStub = shadowhook_hook_sym_name(
            "libc.so",
            "android_get_device_api_level",
            (void *) cProxy,
            nullptr
    );

    if(cStub != nullptr) {
        LOGE("libc hook成功");
    } else{
        LOGE("libc hook失败");
    }
```

```
void* cProxy() {
    LOGE("cproxy");
}
```

libc.so里面符号表里也是这个：
<img width="875" alt="image" src="https://user-images.githubusercontent.com/11388037/195986575-bac8be10-db5f-40ac-a0e4-244ef18b931d.png">

**Comment by caikelun** [comment]
建议先看一下文档。
shadowhook初始化为哪种模式，和proxy函数写法是有关系的。
你hook的这个函数返回int不是void*，你的proxy函数也应该返回一个int。
另外，你是怎么确认没有走到proxy函数的

**Comment by shaomaicheng** [comment]
昨天没太理解对用法，我今天看了下demo重新写了下。
初始化模式我设置的unique
proxy函数我现在是这么写的：

```
void* orig_api_level = nullptr;

typedef int (*type_api_level)();

int unique_api_level(){
    LOGE("unique_api_level");
    return ((type_api_level) orig_api_level)();
}

```
hook的代码是这样：
```
cStub = shadowhook_hook_sym_name(
            "libc.so",
            "android_get_device_api_level",
            (void *)unique_api_level,
            (void **)&orig_api_level
    );
```

我是写了个demo，看调用android_get_device_api_level的时候， proxy 函数里面的日志没有打（LOGE是调了logcat的priint）

**Comment by shaomaicheng** [comment]
我自己又写了个
```
int minecount(){return 10;}
```
和proxy：
```
int inner_unique(){
    LOGE("inner proxy");
    return 111;
}
```
这个是打印了，并且返回了111。
难道是我函数表里找的不对吗。但是如第一个截图，确实是找到了。并且返回的stub也不为null。
顺便这里我有个新疑问，我怎么确认我hook的方法 `readelf` 命令打印的方法表里是哪个呢？

**Comment by caikelun** [comment]
我刚看了下，在ndk头文件里 `android_get_device_api_level` 是个 inline 函数，所以你调用 `android_get_device_api_level` 的逻辑里并没有直接在调用这个函数。

```
__BIONIC_GET_DEVICE_API_LEVEL_INLINE int android_get_device_api_level() {
  char value[92] = { 0 };
  if (__system_property_get("ro.build.version.sdk", value) < 1) return -1;
  int api_level = atoi(value);
  return (api_level > 0) ? api_level : -1;
}
```

**Comment by shaomaicheng** [comment]
这个我看是的。但是另一个例子也不行。。。
libhwui.so的Bitmap：
```
// returns true if rowBytes * height can be represented by a positive int32_t value
// and places that value in size.
static bool computeAllocationSize(size_t rowBytes, int height, size_t* size);
```
符号表里:
```
2334: 00000000001da180    56 FUNC    GLOBAL DEFAULT   15 _ZN7android6Bitmap21computeAllocationSizeEmiPm
```
 我的hook：
```
typedef void* (*bitmap_typede)(size_t rowBytes, int height, size_t* size);
void* proxy(size_t rowBytes, int height, size_t* size) {
    LOGE("图片分配调用");
    LOGE("rowBytes:%zu, height:%d",rowBytes, height);
//    return nullptr;
    return ((bitmap_typede) orig)(rowBytes, height, size);
}

// hook
const char* name ="_ZN7android6Bitmap21computeAllocationSizeEmiPm";
allocateHeapBitmapStub = shadowhook_hook_sym_name(
            "libhwui.so",
            name,
            (void*) proxy,
            (void**) &orig
);
```
这个也是hook函数返回不为null，但是proxy不执行。
但是我看这个 computeAllocationsize 是在 allocationHeapBitmap 里使用的：
<img width="981" alt="image" src="https://user-images.githubusercontent.com/11388037/197340595-7b403c63-87b8-42da-aa53-d6a5a1e896c9.png">
 我尝试hook了一下allocationHeapBitmap:
符号表：
```
_ZN7android6Bitmap18allocateHeapBitmapEP8SkBitmap
_ZN7android6Bitmap18allocateHeapBitmapERK11SkImageInfo
_ZN7android6Bitmap18allocateHeapBitmapEmRK11SkImageInfom
```
我看这三个应该分别对应了Bitmap.h里面的
```
static sk_sp<Bitmap> allocateHeapBitmap(SkBitmap* bitmap);
static sk_sp<Bitmap> allocateHeapBitmap(const SkImageInfo& info);
static sk_sp<Bitmap> allocateHeapBitmap(size_t size, const SkImageInfo& i, size_t rowBytes);
```
于是我分别hook了这3个：
```
typedef void* (*bitmap_typede)(void* bitmap);
void* proxy(void* bitmap) {
    LOGE("图片分配调用");
    return ((bitmap_typede) orig)(bitmap);
}
```

结果分别是：
1. hook成功 proxy没反应
2. hook成功 proxy没反应
3. proxy执行，但是有如下crash：
```
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x60d36ce29ebb52 in tid 31138 (ei.nativebitmap), pid 31138 (ei.nativebitmap)
```
看着调用关系是图上这样，但是现在有2个问题
1个是如何确认没有执行proxy的函数是否执行了
第2个是这个直接返回原函数调用结果的为什么会崩溃，有什么解决办法吗

**Comment by shaomaicheng** [comment]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/11388037/197342214-75a56dd5-b7be-42c0-9841-52fb0412201b.png">
直接Android Studio里面断native点看又是
```
static sk_sp<Bitmap> allocateHeapBitmap(SkBitmap* bitmap);
```
调用过来的。。。。。

**Comment by shaomaicheng** [comment]
看起来这个调用栈是对的，最后会调用第三个函数。因为我打印的size 和 rowBytes 的对的。就是不知道为什么调用orig 的时候崩溃了

**Comment by shaomaicheng** [comment]
看着是sk_sp不是指针所以不能定义成void*吗。。。。

**Comment by shaomaicheng** [comment]
找了个libskia.so 和头文件，换成sk_sp解决了。不过这种不是太麻烦了。
但是 类+方法 的hook是不是只能用 inline hook 这种方法呢。看起来bhook那种不适用与这种？

**Comment by caikelun** [comment]
参数类型和返回值类型的不同，可能导致编译器生成的函数有区别，具体取决于对应arch的函数调用约定和C/C++函数的调用约定。所以如果原函数和proxy函数的参数/返回值类型不同，在运行时传参/传返回值用到的方式/寄存器规则可能有区别，就可能会导致崩溃。一般来说，你可以遵循以下规则：

1. 基本数据类型保持一致即可
2. 类的成员函数添加一个void *参数放在第一个作为this指针

对于结构体和类作为参数返回值，如果你的proxy函数中不需要访问结构体和类的成员，只是透传一下参数和返回值，你可以继续遵循以下规则：

3. 指针类型用 void *代替
4. 结构体或类的实例用以下结构体代替:

```
struct fake {
    uintptr_t placeholder[3];
}
```

参考：
https://zh.wikipedia.org/wiki/%E8%BF%94%E5%9B%9E%E5%80%BC%E4%BC%98%E5%8C%96
https://developer.arm.com/documentation/den0024/a/The-ABI-for-ARM-64-bit-Architecture/Register-use-in-the-AArch64-Procedure-Call-Standard/Indirect-result-location

**Comment by caikelun** [comment]
> 找了个libskia.so 和头文件，换成sk_sp解决了。不过这种不是太麻烦了。 但是 类+方法 的hook是不是只能用 inline hook 这种方法呢。看起来bhook那种不适用与这种？

是否可以用 PLT hook 是看你 hook 的函数调用的方式是否是通过 PLT 执行的，与这个函数是否是类的成员函数没有关系。

**Comment by shaomaicheng** [comment]
嗯嗯，看了下确实是的。这个例子用bhook也可以实现
