### ISSUE TITLE
Everything is completely wrong

### ISSUE THREAD

**Issue by RusJJ** [bytedance/android-inline-hook#31]
### ShadowHook Version

1.0.5

### Android OS Version

11.0

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

Poco X3 Pro

### Describe the Bug

So i just switched from the old Cydia Subtrate to this hook... And now everything is completely bad.
Function's stack/heap is completely broken:
![image](https://user-images.githubusercontent.com/8864329/210544844-d5028393-1918-4ee1-8e99-0943bd4db5b9.png)

**Comment by RusJJ** [comment]
> ...
> void foo() { print("2\n"); }
> void bar() { print("hooked 2!\n");
> ...
> foo();
> shadowhook_hook_func_addr(foo, bar, NULL);
> foo();
> foo();

This code above will print this:
> 2
> hooked 2!
> 2 // Why is this 2 and not "hooked 2"?

**Comment by caikelun** [comment]
If you want some help, please show your initialization code, hook code, proxy function, so that we can solve your problem.

**Comment by RusJJ** [comment]
The hooked function is executed only once. Then it just "unhooks" itself without actual unhooking. The example code is above.

**Comment by RusJJ** [comment]
Hooked function is then NEVER being called

**Comment by RusJJ** [comment]
Hooked function is then NEVER being called

**Comment by caikelun** [comment]
@RusJJ Since you didn't show the **initialization code** and **proxy function**, all I can help you is to remind you: please take a look at the [documentation](https://github.com/bytedance/android-inline-hook/blob/main/doc/manual.md) and [example app](https://github.com/bytedance/android-inline-hook/tree/main/app), and compare the differences with your code. Thank you.

**Comment by daarkmodder** [comment]
This can rate my inline hook 😃.

**Comment by RusJJ** [comment]
> This can rate my inline hook 😃.

Too much of useless AI stuff, not an **inline**. Did my own a year ago and its much better
