### ISSUE TITLE
你好，能支持armeabi架构吗

### ISSUE THREAD

**Issue by anjiuzhe** [bytedance/android-inline-hook#32]
### the Feature, Motivation and Pitch

这个架构比较老了，但有些使用场景只有这个架构，好适配吗？后期能否支持下呢，谢谢大佬

**Comment by caikelun** [comment]
目前的现状是 shadowhook 用 NDK23 编译（为了使用一些 llvm 的新特性来缩小 so 体积和优化性能），但是 armeabi 从 NDK17 开始就不再支持了：

 https://github.com/android/ndk/wiki/Changelog-r17

> Support for ARMv5 (armeabi), MIPS, and MIPS64 has been removed. Attempting to build any of these ABIs will result in an error.

如果在编译打包流程中用 NDK16 再单独编译一份 armeabi 的 so，最终一起打包进 aar 中，理论上是可行的。
@anjiuzhe 我们后面有空会调研下，但是时间没有保证，你如果着急的话，可以自己试试整体改成 NDK16 编译，加入 armeabi 试试。

**Comment by anjiuzhe** [comment]
@caikelun 好的，非常感谢。
