### ISSUE TITLE
shadowhook_hook_sym_name 支持不传入库名

### ISSUE THREAD

**Issue by wlt233** [bytedance/android-inline-hook#36]
### the Feature, Motivation and Pitch

之前使用 `Dobby` 的 `DobbySymbolResolver` 时，库名是可以直接传一个 `NULL` 进去的。粗看了实现大概是在 `dlsym` 的时候传入了 `RTLD_DEFAULT`，请问是否可以实现类似的功能呢？

**Comment by caikelun** [comment]
感谢你的建议，从使用便利性的角度我能理解这个需求，但是基于以下理由我们目前不会考虑支持库名传 `NULL`：

1. 运行效率：如果库名为 `NULL`，无论调用系统的 `dlsym`，还是自己解析 .dynsym 和 .symtab，最坏的情况是需要遍历整个 solist 中所有 ELF 的 .dynsym 和 .symtab，更糟糕的是 .symtab 需要从文件中读取，会造成大量 page fault，这在性能上是不可接受的，shadowhook的定位是在线上使用，并且有些 hook 行为是在启动阶段进行。

2. 兼容性：android 从 7.0 开始有 linker namespace 机制，从符号查找的角度看，最终的结果是 “solist 中会有文件名相同但文件路径不同的 ELF”，也导致了 “同一个符号名可能同时存在于 solist 中的多个 ELF 中”。如果需要 hook 的符号存在于此类 ELF 中，为了唯一确定要 hook 的目标位置，不但库名不能为 `NULL`，库名还必须是完整 pathname，如果只有文件名，那就只能看运行时遍历 solist 的时候哪个 ELF 排在链表前面了，这种不确定性也是不可接受的。从 API 设计的角度，我们想尽量引导用户避开此类潜在的兼容性问题。

欢迎继续讨论。

**Comment by wlt233** [comment]
了解了，感谢回复！
