### ISSUE TITLE
关于打印日志崩溃，是否能提供一个打印日志接口？

### ISSUE THREAD

**Issue by dsfhoewf** [bytedance/android-inline-hook#38]
### the Feature, Motivation and Pitch

hook free的时候，不使用 __android_log_print输出日志就不崩溃，
一打印日志立马崩溃，猜测内部可能调用了free,造成了递归之类的。

### Alternatives

shadowhook 是否能提供一个打印日志的接口？

**Comment by dsfhoewf** [comment]
我试试把，不过就怕写文件的时候，底层也会调用free之类的

**Comment by caikelun** [comment]
你如果都用系统调用（syscall）的话，肯定不会调用到free，free是个用户态的函数。
或者你可以把信息先append到一个内存buffer中，然后在某个时候输出buffer到logcat或者文件，这样性能应该更好一些，很多真实的监控方案都是这么做的。

**Comment by dsfhoewf** [comment]
好的 我试试 感谢建议
