### ISSUE TITLE
Hook 异常

### ISSUE THREAD

**Issue by TestPlanB** [bytedance/android-inline-hook#43]
### ShadowHook Version

1.0.6

### Android OS Version

10

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

PECM30

### Describe the Bug

signal:11 (SIGSEGV),code:1 (SEGV_MAPERR),fault addr:0x10
backtrace:
#00 pc 0000000000145258  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::PrettyMethod(bool)+100)
#01 pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::FindOatMethodFor(art::ArtMethod*, art::PointerSize, bool*).llvm.15275248824354953126+548)
#02 pc 0000000000145c64  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::GetOatQuickMethodHeader(unsigned long)+280)
#03 pc 00000000001ecd10  /apex/com.android.runtime/lib64/libart.so (art::FaultManager::IsInGeneratedCode(siginfo*, void*, bool)+896)
#04 pc 00000000001ec664  /apex/com.android.runtime/lib64/libart.so (art::FaultManager::HandleFault(int, siginfo*, void*)+92)
#05 pc 0000000000004e8c  /system/bin/app_process64 (_ZN3art11SignalChain7HandlerEiP7siginfoPv+588)
#06 pc 00000000000074f4  /data/app/com.lalamove.huolala.driver-MqNwgTqrNxaLEufPVdnWfQ==/lib/arm64/libshadowhook.so
#07 pc 0000000000000628  [vdso]
#08 pc 0000000000571a20  /apex/com.android.runtime/lib64/libart.so (artAllocArrayFromCodeResolvedRegionTLAB+216)
#09 pc 000000000013e584  /apex/com.android.runtime/lib64/libart.so (art_quick_alloc_array_resolved16_region_tlab+132)
#10 pc 000000000024c798  /system/framework/arm64/boot.oat (java.lang.StringBuilder.append+216)
#11 pc 00000000001a2ab8  /memfd:/jit-cache (deleted)

**Comment by caikelun** [comment]
shadowhook集成了bytesig作为native崩溃兜底机制，它都会注册sigsegv和sigbus的signal handler，处理方式类似于art虚拟机的sigchain。并且“shadowhook的signal handler”会比“art sigchain的signal handler”先执行，所以当崩溃发生在系统的信号处理相关逻辑中时，大概率会看到libshadowhook.so，这表示“调用栈”经过了shadowhook，shadowhook发现当前的崩溃信号不是自身导致的崩溃，于是就继续调用“信号处理函数链”中的下一个signal handler。

以下是linux/Android中sigsegv信号在一些典型场景中的“信号处理函数链”，可以理解为：信号从kernel“发出”后，会按照这个“信号处理函数链”的顺序逐个执行对应的信号处理函数：

* linux：无（所以执行了kernel默认的coredump行为）
* Android：debuggerd
* \+ art虚拟机：art sigchain -> debuggerd
* \+ xcrash：art sigchain -> xcrash -> debuggerd
* \+ shadowhook：shadowhook -> art sigchain -> xcrash -> debuggerd

sigbus的“信号处理函数链”类似，只是少了art sigchain，art不关心sigbus。

shadowhook不会注册除sigsegv和sigbus以外的信号处理函数。
