### ISSUE TITLE
sh_linker_init failed on NoxPlayer 6.6.1.5

### ISSUE THREAD

**Issue by supernghia89** [bytedance/android-inline-hook#45]
### ShadowHook Version

1.0.7

### Android OS Version

5.1.1

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

NoxPlayer 6.6.1.5

### Describe the Bug

Hi,

`shadowhook_init(SHADOWHOOK_MODE_UNIQUE, false)` returned error code 12.

With `api_level = 22`, function `xdl_dsym` could not find `__dl__Z9do_dlopenPKciPK17android_dlextinfo` in `linker`, thus the result returned for `sh_linker_dlopen_addr` is `null`.

I have attached the linker binary file bellow

Regards.
[linker.zip](https://github.com/bytedance/android-inline-hook/files/12333547/linker.zip)

**Comment by caikelun** [comment]
Thanks for your feedback. ShadowHook has no plan to support android emulator yet.

**Comment by supernghia89** [comment]
Thank you~

I have also found some bugs in the Bluestacks emulator. I hope you have plans to support the emulator in the future.
