### ISSUE TITLE
android inline hook hook dlopen crash

### ISSUE THREAD

**Issue by xiaoyur347** [bytedance/android-inline-hook#48]
### ShadowHook Version

1.0.7

### Android OS Version

8.0

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

Google Pixel 2 XL

### Describe the Bug

需要hook dlopen，此为前提。
static void *(*old_dlopen)(const char* filename, int flags);
void *new_dlopen(const char* filename, int flags)
{
    return old_dlopen(filename, flags);
}
尝试了unique模式，调用shadowhook_hook_sym_addr(dlopen, (void*)new_dlopen, (void**)&old_dlopen);
在android 8上会因为namespace导致失败。
失败的原因有几个：
1、sh_linker.c中static uintptr_t sh_linker_dlopen_addr;  // save address of dlopen(==4.x) or do_dlopen(>=5.0)这个变量设计的不太合理，应该再增加一个static uintptr_t sh_linker_dlopen_addr_ro;以避免因为sh_linker_dlopen_addr修改导致无法判断是否用户想要hook dlopen。

```sh
__attribute__((constructor)) static void sh_linker_ctor(void) {
  sh_linker_dlopen_addr_ro = (uintptr_t)dlopen;
  sh_linker_dlopen_addr = (uintptr_t)dlopen;
bool sh_linker_need_to_hook_dlopen(uintptr_t target_addr) {
  return SHADOWHOOK_IS_UNIQUE_MODE && !sh_linker_dlopen_hooked && target_addr == sh_linker_dlopen_addr_ro;
}
```

2、
```sh
if (sh_linker_need_to_hook_dlopen(self->target_addr)) {
    SH_LOG_INFO("task: hook dlopen/do_dlopen internal. target-address %" PRIxPTR, self->target_addr);
    if (0 != (r = sh_task_start_monitor(false))) goto end;
    // 这里也有问题，内部已经hook dlopen的情况下，是否应该挂个链式的hook来返回。
  }
```

疑问，是否我应该切换成shared模式。
但是看起来shared模式也不会默认hook dlopen。要hook dlopen需要设置为未加载库时hook未加载库的方法名才会。

**Comment by caikelun** [comment]
@xiaoyur347 

1. sh_linker 模块中 dlopen 相关的逻辑，大致目的是这样的：

shadowhook 有个特性，当通过库名 + 符号名 hook 一个函数时，如果 shadowhook 发现这个库还没有被加载到内存中，则返回状态值 pending，表示这个 hook task 当前未完成，但是 shadowhook 内部已经记录了这个 task，后续当这个库被加载到内存时，会去执行这个 hook task 的。

因此，shadowhook 需要一种方法去感知“新动态库何时被加载到内存”，于是，在 android 4.x 中 shadowhook 内部 hook 了 dlopen，在 >= android 5.0 中 shadowhook 内部 hook 了 do_dlopen。之所以有这个区别，是因为 android 7.0 开始的 linker namespace 限制，如果在 >= android 7.0 的情况下 hook dlopen，则在 dlopen proxy 中调用 dlopen 的原函数时，LR 寄存器的值实际已经落在 proxy 函数中了，dlopen 的实现机制中是通过 LR 来判断 namespace 的，于是就可能 dlopen 失败。在 >= android 7.0 中改为 hook do_dlopen 则可以避开这个问题，具体可以看下 linker 这部分的源码逻辑。android 5.x 和 6.x 中其实 hook dlopen 或 do_dlopen 都可以，android 4.x 中没有导出 do_dlopen 符号所以 hook 了 dlopen。

sh_linker 中对 dlopen（或 do_dlopen）的操作，是为了确保“如果外部刚好也需要 hook dlopen（或 do_dlopen）”时，shadowhook 需要抢先一步先 hook 这个函数，这样 shadowhook 对这个函数的 proxy 函数就能先执行。因为外部的 dlopen proxy 也许出于某种原因会“不调用 dlopen 原函数”，那么 shadowhook 就可能会漏掉之前记录的 pending hook task 了。

2. 具体到你的问题：

首先，你 hook 后发生 crash 的原因可能是 dlopen 原函数逻辑中发现 LR 的 namespace 不匹配，于是 hook 后加载某些动态库失败了。这和 shadowhook 的 sh_linker 模块应该没有关系，因为在 >= android 5.0 时，shadowhook 内部不会 hook dlopen，而是在需要时 hook do_dlopen。

我觉得你最方便的处理方式是改为 hook do_dlopen，这样 LR 是作为一个参数传入的，就绕过了 dlopen 原函数中动态获取 LR 的逻辑。具体可以参照 sh_linker 中 hook do_dlopen 的逻辑（不同 android 版本中 do_dlopen 的函数签名有差异）。
