### ISSUE TITLE
g_dl_mutex的symbol

### ISSUE THREAD

**Issue by ScalletaZ** [bytedance/android-inline-hook#50]
### ShadowHook Version

1.8.0

### Android OS Version

14

### Android ABIs

armeabi-v7a, arm64-v8a

### Device Manufacturers and Models

aosp

### Describe the Bug

aosp最新的g_dl_mutex的symbol变成了__dl_g_dl_mutex

**Comment by caikelun** [comment]
一直都是 `__dl__ZL10g_dl_mutex`，你可以再确认下：

```
$ adb pull /system/bin/linker
$ llvm-readelf -sW ./linker | grep __dl__ZL10g_dl_mutex
     5: 000d5f20     4 OBJECT  LOCAL  DEFAULT    18 __dl__ZL10g_dl_mutex

$ adb pull /system/bin/linker64
$ llvm-readelf -sW ./linker64 | grep __dl__ZL10g_dl_mutex
     4: 000000000014bee0    40 OBJECT  LOCAL  DEFAULT    18 __dl__ZL10g_dl_mutex
```

**Comment by caikelun** [comment]
> 嗯 9.8的gsi还是正常 ci.android.com 上面的已经变了 不知道下个gsi会不会发

能贴个具体的地址吗？从哪里看出变成了 `__dl_g_dl_mutex`？

**Comment by mskmkt0704** [comment]
我的设备已经确定变成了 __dl_g_dl_mutex，而且变成了 hidden
Device: Pixel 6
Build Number: AP11.231020.013.A1
```
$ readelf -sW ./linker | grep g_dl_mutex
    50: 000d96e0     4 OBJECT  LOCAL  HIDDEN    18 __dl_g_dl_mutex
$ readelf -sW ./linker64 | grep g_dl_mutex
  4597: 000000000014e040    40 OBJECT  LOCAL  HIDDEN    18 __dl_g_dl_mutex
```

**Comment by caikelun** [comment]
> 我的设备已经确定变成了 __dl_g_dl_mutex，而且变成了 hidden Device: Pixel 6 Build Number: AP11.231020.013.A1
> 
> ```
> $ readelf -sW ./linker | grep g_dl_mutex
>     50: 000d96e0     4 OBJECT  LOCAL  HIDDEN    18 __dl_g_dl_mutex
> $ readelf -sW ./linker64 | grep g_dl_mutex
>   4597: 000000000014e040    40 OBJECT  LOCAL  HIDDEN    18 __dl_g_dl_mutex
> ```

https://developers.google.com/android/images#oriole
没找到 Pixel 6 Build Number: AP11.231020.013.A1 的 image，能问下具体是上面链接中 factory images 中的哪个吗？

**Comment by mskmkt0704** [comment]
我是通过 OTA 更新的，查了下网页确实没有，可能要等后续谷歌更新到网页

**Comment by caikelun** [comment]
@ScalletaZ @mskmkt0704 实在抱歉，之前耽搁了这个问题的处理。刚测试了 Android 14 QPR2 Beta 版本，确实有这个问题，感谢两位的指出。刚发布了一个新版本 `1.0.9` 修复了这个 bug：https://github.com/bytedance/android-inline-hook/releases/tag/v1.0.9
