### ISSUE TITLE
Hook __usercall 函数会破坏x8寄存器数据导致崩溃

### ISSUE THREAD

**Issue by zjhsdcc** [bytedance/android-inline-hook#56]
### ShadowHook Version

所有版本

### Android OS Version

10.0

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

Pxiel 3

### Describe the Bug

测试手机：Pixel 3
安卓OS   :  10.0
HOOK方法：( IDA显示为__usercall类型，
      文件：frameworks/base/libs/androidfw/ApkAssets.cpp
      方法：std::unique_ptr<Asset> ApkAssets::Open(const std::string& path, Asset::AccessMode mode)
![image](https://github.com/bytedance/android-inline-hook/assets/18672771/c2606ae0-4463-4e71-ac21-c218584c6a1b)
崩溃日志：
![image](https://github.com/bytedance/android-inline-hook/assets/18672771/0e85c50e-2f5d-4702-9d15-b4355d12da18)

**Comment by halo2me** [comment]
@zjhsdcc 你好，请问这个问题是如何解决的？
