### ISSUE TITLE
CPP SHADOWHOOK_CALL_PREV 宏漏了解引用函数指针

### ISSUE THREAD

**Issue by liusj5257** [bytedance/android-inline-hook#57]
### ShadowHook Version

1.0.9

### Android OS Version

33

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

1

### Describe the Bug

#define SHADOWHOOK_CALL_PREV(func, ...) \
  (*(decltype(&(func)))shadowhook_get_prev_func((void *)(func)))(__VA_ARGS__)
 使用CPP需要修改宏SHADOWHOOK_CALL_PREV
 handle =
        SHADOWHOOK_CALL_PREV(linker_proxy_do_dlopen_l, name, flags, extinfo);

**Comment by caikelun** [comment]
使用`函数指针类型`时，加 `*` 或者不加在语法上都是可以的，编译后生成的汇编指令也是一样的，运行效果也是一样的。
