### ISSUE TITLE
Hook failing when called from shared library constructor

### ISSUE THREAD

**Issue by reveny** [bytedance/android-inline-hook#60]
### ShadowHook Version

1.0.9

### Android OS Version

14

### Android ABIs

armeabi-v7a, arm64-v8a

### Device Manufacturers and Models

Samsung and others

### Describe the Bug

When building a shared library (no matter the compiler flags) and using a library constructor like below
`
__attribute__((constructor))
void init() {
    ...
}
`

Shadowhook fails with the error:
8 - Init bytesig SIGSEGV mod failed.

However, when loading from JNI_OnLoad, this does not seem to be an issue and the hook works just fine there.
I'm trying to hook mmap from libc here.

**Comment by caikelun** [comment]
Hi @reveny,

I tried it with the systest module that comes with the shadowhook project:

1. Comment out the following code in the [SysTest.java](https://github.com/bytedance/android-inline-hook/blob/main/systest/src/main/java/com/bytedance/shadowhook/systest/SysTest.java#L41-L48) file:

```Java
// initErrno = ShadowHook.init(new ShadowHook.ConfigBuilder()
//     .setMode(sharedMode ? ShadowHook.Mode.SHARED : ShadowHook.Mode.UNIQUE)
//     .setDebuggable(debuggable)
//     .setRecordable(recordable)
//     .build());
// if(0 != initErrno) {
//     return initErrno;
// }
```

2. Add a library constructor in [systest_jni.c](https://github.com/bytedance/android-inline-hook/blob/main/systest/src/main/cpp/systest_jni.c):

```C
#include <android/log.h>
#include "shadowhook.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgnu-zero-variadic-macro-arguments"
#define LOG(fmt, ...) __android_log_print(ANDROID_LOG_INFO, "shadowhook_tag", fmt, ##__VA_ARGS__)
#pragma clang diagnostic pop

__attribute__((constructor)) static void systest_init(void) {
  int r = shadowhook_init(SHADOWHOOK_MODE_SHARED, false);
  LOG("shadowhook_init ret: %d", r);
}
```

3. I found it works and no errors were found:

```
$ adb logcat -s shadowhook_tag
--------- beginning of main
04-15 14:38:56.317 20915 20915 W shadowhook_tag: shadowhook version 1.0.10-alpha.0: shadowhook init(mode: SHARED, debuggable: false), return: 0, real-init: yes
04-15 14:38:56.317 20915 20915 I shadowhook_tag: shadowhook_init ret: 0
```

Is there any difference between my usage and yours?

**Comment by reveny** [comment]
I have finally figured it out, it was caused by a custom made llvm obfuscator being poorly made and thus causing issues. I apologize for opening this issue. Problem was caused from my own setup.

**Comment by intelligentpotato** [comment]
Hi @caikelun,

Appreciate you looking into the issues and answering all our questions.

Unfortunately, I'm having the same issue. Tried both SHARED and UNIQUE modes.

`
06-22 01:04:00.053 29766 29766 W shadowhook_tag: shadowhook version 1.0.9: shadowhook init(mode: UNIQUE, debuggable: false), return: 8, real-init: yes
06-22 01:04:00.053 29766 29766 I shadowhook_tag: shadowhook_init ret: 8
`

Prior to that in logcat there's the following warning from SELinux:
`
06-22 01:04:00.049 29766 29766 I com.whatsapp: type=1400 audit(0.0:1334): avc: denied { execute } for path="/data/local/tmp/libnativelib.so" dev="sda17" ino=2793478 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=file permissive=1 app=com.whatsapp
`

However, after setting the proper security context via
`
chcon u:object_r:app_data_file:s0:c197,c256,c512,c768 libnativelib.so
`

I'm seeing
`
06-22 01:09:25.846 29947 29947 W com.whatsapp: type=1400 audit(0.0:2141): avc: granted { execute } for path="/data/local/tmp/libnativelib.so" dev="sda17" ino=2793478 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c197,c256,c512,c768 tclass=file app=com.whatsapp
`

But shadowhook still can't initialize with the status code 8.

I am using https://github.com/MJx0/AndKittyInjector to inject my native library into the target app. Dobby works fine with it.

**Comment by reveny** [comment]
> Hi @caikelun,
> 
> Appreciate you looking into the issues and answering all our questions.
> 
> Unfortunately, I'm having the same issue. Tried both SHARED and UNIQUE modes.
> 
> `06-22 01:04:00.053 29766 29766 W shadowhook_tag: shadowhook version 1.0.9: shadowhook init(mode: UNIQUE, debuggable: false), return: 8, real-init: yes 06-22 01:04:00.053 29766 29766 I shadowhook_tag: shadowhook_init ret: 8`
> 
> Prior to that in logcat there's the following warning from SELinux: `06-22 01:04:00.049 29766 29766 I com.whatsapp: type=1400 audit(0.0:1334): avc: denied { execute } for path="/data/local/tmp/libnativelib.so" dev="sda17" ino=2793478 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=file permissive=1 app=com.whatsapp`
> 
> However, after setting the proper security context via `chcon u:object_r:app_data_file:s0:c197,c256,c512,c768 libnativelib.so`
> 
> I'm seeing `06-22 01:09:25.846 29947 29947 W com.whatsapp: type=1400 audit(0.0:2141): avc: granted { execute } for path="/data/local/tmp/libnativelib.so" dev="sda17" ino=2793478 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c197,c256,c512,c768 tclass=file app=com.whatsapp`
> 
> But shadowhook still can't initialize with the status code 8.
> 
> I am using https://github.com/MJx0/AndKittyInjector to inject my native library into the target app. Dobby works fine with it.

If you are injecting I assume you built shadowhook directly into the library which from my experience will not work.

**Comment by intelligentpotato** [comment]
@reveny Yes, I'm statically linking shadowhook to my code. Thanks!
Theoretically, if I inject shadowhook and my own code separately, would it work?

**Comment by reveny** [comment]
> @reveny Yes, I'm statically linking shadowhook to my code. Thanks! Theoretically, if I inject shadowhook and my own code separately, would it work?

I don't think that's going to work but maybe wait for @caikelun to respond
