### ISSUE TITLE
能不能添加一个shadowhook_dlopen之后获取so基质的方法，类似andhook的AKGetBaseAddress

### ISSUE THREAD

**Issue by c01ns** [bytedance/android-inline-hook#61]
### the Feature, Motivation and Pitch

能不能添加一个shadowhook_dlopen之后获取so基质的方法，类似Andhook的AKGetBaseAddress

**Comment by caikelun** [comment]
不会添加。shadowhook的shadowhook_dlopen和shadowhook_dlsym只是用于方便用户批量获取函数地址，然后再调用shadowhook_hook_addr执行hook用的，不想在shadowhook的public API中添加与核心功能无关的内容。

你可以试试 [xDL](https://github.com/hexhacking/xDL) 的 `xdl_info`。
