### ISSUE TITLE
Hook clock_gettime ANR

### ISSUE THREAD

**Issue by 994955138** [bytedance/android-inline-hook#65]
### ShadowHook Version

1.0.9

### Android OS Version

11

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

Google Pixel 4

### Describe the Bug

在主线程 Hook clock_gettime 之后，直接卡死。内存和CPU没有明显波动，没有任何日志。继续操作界面则ANR

**Comment by caikelun** [comment]
你可以贴一下你的 shadowhook 初始化代码、hook 代码、proxy 函数。

**Comment by 994955138** [comment]
已经解决了，是我的代理函数打印了日志，并且代理函数调用频率过高导致的。
