### ISSUE TITLE
为什么有时会报这个问题

### ISSUE THREAD

**Issue by shuajinanhai** [bytedance/android-inline-hook#66]
### ShadowHook Version

 1.0.9

### Android OS Version

14

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

小米6 14系统

### Describe the Bug

shadowhook: hook_func_addr(0x770af72820, 0x73da265a04) ...
task: get dlinfo by target addr: target_addr 0x770af72820, sym_name (NULL), sym_sz 0, load_bias 0, pathname (NULL)
shadowhook: hook_func_addr(0x770af72820, 0x73da265a04) FAILED. 22 - Find dlinfo failed
也没进hook函数，游戏也没崩溃
为啥会报这个问题呢

**Comment by caikelun** [comment]
`hook_func_addr` 函数中的 `func_addr` 参数必须指向内存中某个 ELF 中的某个函数的头部地址。

这个信息说明：通过 `0x770af72820` 这个地址无法获取到它对应的 ELF 信息（指“通过`dladdr`获取的 `dli_fbase`），也可以理解为 `0x770af72820` 无法对应到内存中的某个 ELF。你可以打印 maps 信息对应一下。
