### ISSUE TITLE
Too many init error reports when use UNIQUE on Android 14, ErrorCode = 12, SHADOWHOOK_ERRNO_INIT_LINKER.

### ISSUE THREAD

**Issue by Edison0716** [bytedance/android-inline-hook#67]
### ShadowHook Version

1.0.8

### Android OS Version

14.0

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

RedMi POCO XIAOMI

### Describe the Bug

![image](https://github.com/bytedance/android-inline-hook/assets/8669094/d42d3e30-eb18-451d-8fde-28d87d7162ef)

**Comment by Edison0716** [comment]
![image](https://github.com/bytedance/android-inline-hook/assets/8669094/4e273f81-7b1c-4e8a-851a-90ee9cd8e7dc)


@caikelun 你好 这笔提交是适配 Android 14 的一个版本的改动对吧  看也是针对UNIQUE 模式的，是否解决我的问题呢？

**Comment by caikelun** [comment]
这是个已经解决的问题。Android 14 QPR2 引入了一个兼容性问题（linker 的一个内部符号名称改变），导致 shadowhook 初始化失败，请升级到 shadowhook 1.0.9 版本 https://github.com/bytedance/android-inline-hook/releases/tag/v1.0.9

**Comment by Edison0716** [comment]
好的 已升级 谢谢
