### ISSUE TITLE
hook本应用的so库报错：Symbol size too small

### ISSUE THREAD

**Issue by anjiuzhe** [bytedance/android-inline-hook#81]
### ShadowHook Version

1.0.10

### Android OS Version

9.0

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

雷电模拟器

### Describe the Bug

你好，v8a架构在真机和模拟器均表现正常，v7a架构只有在真机表现正常，v7a在模拟器报错：Symbol size too small，请问这个是什么原因导致的呢？

**Comment by Colibrow** [comment]
可以把v7a目标函数的汇编指令发出来看看

**Comment by anjiuzhe** [comment]
@Colibrow 你好，这个是v7a的so库地址，[https://gitee.com/anruoxi3475/public/blob/master/libil2cpp.so]()，hook的il2cpp_class_from_name函数，内部汇编指令代码请看下面图片：
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/418627c3-1290-49d4-84cf-5b5e05087725">
<img width="801" alt="image" src="https://github.com/user-attachments/assets/b86a5a47-eaf1-4f90-887e-d8e049000096">

**Comment by anjiuzhe** [comment]
@Colibrow 这个是log日志：
![log](https://github.com/user-attachments/assets/36aa031d-b401-41bb-b7f2-d03e99ffee2d)

**Comment by anjiuzhe** [comment]
手机运行正常，日志如下：
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/63474c81-e84b-4d90-b26a-b4dad8da8924">

**Comment by Colibrow** [comment]
根据模拟器日志，在分配跳板空间的时候会经历三个步骤层层兜底

1. 目标地址附近mmap寻找可用空间失败
2. 目标ELF文件末尾对齐位置找到可用空间，但是尝试使用这块空间报错，具体需要调试代码`sh_exit_try_alloc_in_library`
3. 在v7a情况下绝对地址作为跳板需要8个字节，目标函数是4个字节，函数指令长度太短所以hook失败

因为目前shadowhook不支持模拟器，所以你可以手动在模拟器上调试一下看看是哪一步出问题，很大可能是因为模拟器对mprotect进行了一些限制

**Comment by anjiuzhe** [comment]
好的，感觉解答。
