### ISSUE TITLE
能支持静态链接吗

### ISSUE THREAD

**Issue by qq6r** [bytedance/android-inline-hook#9]
### the Feature, Motivation and Pitch

想整合到自己的so中,目前好像不支持静态链接

**Comment by caikelun** [comment]
你可以自己从源码编译。我们不会提供静态库，因为LLVM有很多编译选项是和静态链接选项紧密配合的，比如LTO、outliner。所以没法预先假设静态链接选项是如何配置的，众口难调。

**Comment by qq6r** [comment]
好的
